---
# tasks file for consul

- name: Create consul group
  group:
    name: consul
    system: yes
    state: present
  tags:
    - setup
    - consul

- name: Create consul user
  user:
    name: consul
    group: consul
    system: yes
    state: present
  tags:
    - setup
    - consul

- name: Install requirements
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ consul_packages }}"
    - "{{ consul_additional_packages }}"
  tags:
    - package
    - consul

- name: Install pip requirements
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ consul_python_packages }}"
    - "{{ consul_python_additional_packages }}"
  tags:
    - package
    - consul

- name: Create config directory
  file:
    path: /etc/consul
    owner: root
    group: root
    mode: 0755
    state: directory
  tags:
    - setup
    - consul

- name: Create Data directory
  file:
    path: /var/lib/consul
    owner: consul
    group: consul
    mode: 0755
    state: directory
  tags:
    - setup
    - consul

- name: Download and install consul
  unarchive:
    src: "{{ consul_binary_url }}"
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    creates: "/usr/local/bin/consul"
  tags:
    - setup
    - consul

- name: Create Consul configuration
  copy:
    content: "{{ consul_config | mandatory | to_nice_json }}"
    dest: "/etc/consul/config.json"
    owner: consul
    group: consul
    mode: 0640
  notify: reload consul
  tags:
    - config
    - consul

- name: Setup systemd file
  template:
    src: systemd.j2
    dest: /lib/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  tags:
    - setup
    - consul

- name: Enable service
  service:
    name: consul
    enabled: yes
    state: started
  tags:
    - service
    - consul
